= Geographical Names Creation & Maintenance Standard

_This proposed standard is based on the draft https://icsm-au.github.io/addr-creation-maintenance/doc.html[Australian Addressing Creation & Maintenance Standard] with which it will be aligned and cross-referenced._

_This proposed standard will be dependent on the https://linked.data.gov.au/def/gn[Geographical Names Model] when it's approved as a standard, much like the_ Addressing Creation & Maintenance Standard _is dependent on the https://linked.data.gov.au/def/addr[Address Model]._

This proposed standard is rendered on, as it is being developed, at:

* https://linked.data.gov.au/def/gn-cm

== Contributions

We encourage all contributions to this Standard!

Please contribute by:

. Raising concerns/ideas within ICSM's Address Working Group
. Creating Issue tickets within this repository's Issue Tracker
.. at https://github.com/Spatial-Information-QLD/addr-creation-maintenance/issues
. Creating Pull Requests to absorb changes against the document source files
.. the source files are in the `document/` folder of this repository
.. Pull Requests should be lodged at https://github.com/Spatial-Information-QLD/addr-creation-maintenance/pulls

_If creating Pull Requests is a new/unknown thing for you, please communicate with the contacts below for help._

== Rights and License

The information in this repository is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 license], see the LICENSE file for the deed.

&copy; Intergovernmental Committee on Survey ing and Mapping, 2024


== Contacts

For more information about these vocabularies, contact:

*Spatial Information* +
GeoResources Division +
Department of Resources +
Queensland Government +
AddressQueensland@resources.qld.gov.au

For further information, please visit:

https://www.resources.qld.gov.au/data-mapping +
https://qldspatial.information.qld.gov.au/

For technical model implementation questions, contact:

*Nicholas Car* +
https://kurrawong.ai[KurrawongAI] +
nick@kurrawong.ai +
_Contractor to Spatial Information Qld._
