= Geographical Names Creation & Maintenance Standard

This (proposed) standard codifies roles and tasks involved in the creation and maintenance of Geographical Names in Australia and New Zealand under the authority of the https://www.icsm.gov.au/[Intergovernmental Committee on Surveying & Mapping].

_This standard is dependent on the (proposed) https://linked.data.gov.au/def/gn[Geographical Names Model]._

_This proposed standard is based on the draft https://linked.data.gov.au/def/addr-cm[Addressing Creation & Maintenance Standard] with which it will be aligned and cross-referenced._

This repository contains the source code for the standard and the standard document is rendered from these files online at:

*  https://linked.data.gov.au/def/gn-cm


== Contributions

We encourage all contributions to this Standard!

Please contribute by:

. Raising concerns/ideas within ICSM's Geographical Names Working Group
. Creating Issue tickets within this repository's Issue Tracker
.. at https://github.com/Spatial-Information-QLD/addr-creation-maintenance/issues
. Creating Pull Requests to absorb changes against the document source files
.. the source files are in the `document/` folder of this repository
.. Pull Requests should be lodged at https://github.com/Spatial-Information-QLD/addr-creation-maintenance/pulls

_If creating Pull Requests is a new/unknown thing for you, please communicate with the contacts below for help._


== Rights and License

The information in this repository is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 license], see the LICENSE file for the deed.

&copy; Intergovernmental Committee on Survey ing and Mapping, 2024


== Contacts

For more information about these vocabularies, contact:

*Spatial Information* +
GeoResources Division +
Department of Resources +
Queensland Government +
AddressQueensland@resources.qld.gov.au

For further information, please visit:

https://www.resources.qld.gov.au/data-mapping +
https://qldspatial.information.qld.gov.au/

For technical model implementation questions, contact:

*Nicholas Car* +
https://kurrawong.ai[KurrawongAI] +
nick@kurrawong.ai +
_Contractor to Spatial Information Qld._


== Document generation

This document is developed using the https://asciidoc.org/[ASCIIDOC] document system used for many https://www.ogc.org/[OGC] and https://www.iso.org/home.html[ISO] standards. It essentially builds HTML or PDF documents from a series of text files (ending in `.adoc`), images and so, with certain styling conventions.

This repository automatically builds this document from the source files in the `document/` folder using the https://asciidoctor.org/[ASCIIDoctor] tool that it integrated into a GitHub Action, meaning the document is rebuild with every error-free update to the source files here.

The auto-built document is online at https://icsm-au.github.io/addr-creation-maintenance/doc.html.